export default [
  { demon: "Aamon/Amon", religion: "Christian demonology" },
  { demon: "Abaddon/Apollyon", religion: "Christian demonology" },
  { demon: "Abezethibou", religion: "Jewish demonology" },
  { demon: "Abraxas", religion: "Gnosticism" },
  { demon: "Abyzou", religion: "Jewish mythology" },
  {
    demon: "Adrammelech",
    religion: "Assyrian mythology, Christian demonology"
  },
  { demon: "Aeshma", religion: "Zoroastrianism" },
  { demon: "Agaliarept", religion: "Jewish mythology" },
  { demon: "Agrat", religion: "Jewish demonology" },
  { demon: "Agares", religion: "Christian demonology" },
  { demon: "Agiel", religion: "Jewish mythology" },
  { demon: "Ahriman/Angra", religion: "Zoroastrianism" },
  { demon: "Aim/Haborym", religion: "Christian demonology" },
  { demon: "Aka", religion: "Zoroastrianism" },
  { demon: "Ala", religion: "Slavic mythology" },
  { demon: "Alal", religion: "Chaldean mythology" },
  { demon: "Alastor", religion: "Christian demonology" },
  { demon: "Allocer/Alloces", religion: "Christian demonology" },
  { demon: "Alû", religion: "Akkadian mythology" },
  { demon: "Amaymon", religion: "Christian demonology" },
  { demon: "Amdusias", religion: "Christian demonology" },
  { demon: "Amy-(demon)", religion: "Christian demonology" },
  { demon: "Anammelech", religion: "Assyrian mythology" },
  { demon: "Ancitif", religion: "Christian demonology" },
  { demon: "Andhaka", religion: "Hindu mythology" },
  { demon: "Andras", religion: "Christian demonology" },
  { demon: "Andrealphus", religion: "Christian demonology" },
  { demon: "Andromalius", religion: "Christian demonology" },
  { demon: "Antichrist", religion: "Christian eschatology" },
  { demon: "Anzu", religion: "Sumerian mythology" },
  { demon: "Apep", religion: "Egyptian mythology" },
  { demon: "Armaros", religion: "Jewish demonology" },
  { demon: "Archon", religion: "Gnosticism" },
  { demon: "Arunasura", religion: "Hindu mythology" },
  { demon: "Asag", religion: "Sumerian demonology" },
  { demon: "Asakku", religion: "Babylonian mythology" },
  { demon: "Asb'el", religion: "Jewish mythology" },
  {
    demon: "Asmodai/Asmodeus",
    religion: "Jewish folklore, Christian mythology, Islamic folklore"
  },
  { demon: "Astaroth", religion: "Christian demonology" },
  { demon: "Asura", religion: "Hindu mythology" },
  { demon: "Azazel/Azaz'el", religion: "Jewish mythology, Islamic mythology" },
  { demon: "Azi", religion: "Zoroastrianism" },
  { demon: "Baal/Bael", religion: "Christian demonology" },
  { demon: "Babi", religion: "Indonesian mythology" },
  { demon: "Bakasura", religion: "Hindu mythology" },
  { demon: "Baku", religion: "Japanese mythology" },
  { demon: "Balam", religion: "Christian demonology" },
  { demon: "Balberith", religion: "Jewish demonology" },
  { demon: "Bali", religion: "Hindu mythology" },
  { demon: "Banshee", religion: "Irish mythology" },
  { demon: "Baphomet", religion: "Christian folklore" },
  { demon: "Barbas", religion: "Christian demonology" },
  { demon: "Barbatos", religion: "Christian demonology" },
  { demon: "Barong", religion: "Indonesian mythology" },
  { demon: "Bathin/Mathim/Bathym/Marthim", religion: "Christian demonology" },
  { demon: "Beelzebub", religion: "Jewish and Christian demonology" },
  { demon: "Behemoth", religion: "Jewish and Christian mythology" },
  { demon: "Belial", religion: "Jewish Christian demonology" },
  { demon: "Beleth", religion: "Christian demonology" },
  { demon: "Belphegor", religion: "Christian demonology" },
  {
    demon: "Berith/Beherit",
    religion: "Phoenician mythology, Christian demonology"
  },
  { demon: "Bhūta", religion: "Hindu mythology" },
  { demon: "Bifrons", religion: "Christian demonology" },
  { demon: "Boruta", religion: "Slavic mythology" },
  { demon: "Botis", religion: "Christian demonology" },
  { demon: "Buer", religion: "Christian demonology" },
  { demon: "Bukavac", religion: "Slavic mythology" },
  { demon: "Bune", religion: "Christian demonology" },
  { demon: "Bushyasta", religion: "Zoroastrianism" },
  { demon: "Caim/Canio", religion: "Christian demonology, Scientology" },
  { demon: "Charun", religion: "Etruscan mythology" },
  { demon: "Chemosh", religion: "Moabite mythology" },
  { demon: "Choronzon", religion: "Thelema" },
  { demon: "Chort", religion: "Slavic mythology" },
  { demon: "Cimejes/Kimaris/Cimeies", religion: "Christian demonology" },
  { demon: "Corson", religion: "Christian demonology" },
  { demon: "Crocell/Procell", religion: "Christian demonology" },
  { demon: "Culsu", religion: "Etruscan mythology" },
  { demon: "Daeva", religion: "Zoroastrianism" },
  { demon: "Dagon", religion: "Semitic mythology" },
  { demon: "Dajjal", religion: "Islamic eschatology" },
  { demon: "Dantalion", religion: "Christian demonology" },
  { demon: "Danjal", religion: "Jewish mythology" },
  { demon: "Decarabia", religion: "Christian demonology" },
  { demon: "Demiurge", religion: "Gnostic mythology" },
  { demon: "Demogorgon", religion: "Christian demonology" },
  { demon: "Devil", religion: "Christian demonology" },
  { demon: "Div-e", religion: "Persian mythology" },
  { demon: "Djall", religion: "Albanian mythology" },
  { demon: "Drekavac", religion: "Slavic mythology" },
  { demon: "Dzoavits", religion: "Native American mythology" },
  { demon: "Eblis", religion: " Islamic demonology" },
  { demon: "Eligos", religion: "Christian demonology" },
  { demon: "Eisheth", religion: "Jewish demonology" },
  { demon: "Erlik", religion: "Turkish mythology" },
  { demon: "Focalor", religion: "Christian demonology" },
  { demon: "Foras/Forcas/Forras", religion: "Christian demonology" },
  { demon: "Forneus", religion: "Christian demonology" },
  { demon: "Furcas/Forcas", religion: "Christian demonology" },
  { demon: "Furfur", religion: "Christian demonology" },
  { demon: "Gaap", religion: "Christian demonology" },
  { demon: "Gader'el", religion: "Jewish demonology" },
  { demon: "Gaki", religion: "Japanese mythology" },
  { demon: "Gamigin", religion: "Christian demonology" },
  { demon: "Ghoul", religion: "Arabian" },
  {
    demon:
      "Glasya-Labolas/Caacrinolaas",
    religion: "Christian demonology"
  },
  { demon: "Gorgon", religion: "Greek mythology" },
  { demon: "Gremory/Gomory", religion: "Christian demonology" },
  { demon: "Grigori", religion: "Jewish demonology" },
  { demon: "Gualichu", religion: "Mapuche mythology" },
  { demon: "Guayota", religion: "Guanche mythology" },
  { demon: "Gusion/Gusoin/Gusoyn", religion: "Christian demonology" },
  { demon: "Haagenti", religion: "Christian demonology" },
  { demon: "Halphas/Malthus", religion: "Christian demonology" },
  {
    demon: "Haures/Flauros/Flavros/Hauras/Havres",
    religion: "Christian demonology"
  },
  { demon: "Hinn", religion: "Islamic folklore" },
  { demon: "Ifrit", religion: "Islamic mythology" },
  { demon: "Incubus", religion: "Christian demonology" },
  { demon: "Ipos/Ipes", religion: "Christian demonology" },
  { demon: "Jinn", religion: "Islamic demonology" },
  { demon: "Jikininki", religion: "Japanese mythology" },
  { demon: "Kabandha/Kabhanda", religion: "Hindu mythology" },
  { demon: "Kara", religion: "Turkish mythology" },
  { demon: "Kasadya", religion: "Jewish demonology" },
  { demon: "Kokabiel", religion: "Jewish mythology" },
  { demon: "Kroni", religion: "Ayyavazhi demonology" },
  { demon: "Krampus", religion: "Germanic-Christian demonology" },
  { demon: "Killakee", religion: "Hell-Fire-Club" },
  { demon: "Kukudh", religion: "Albanian mythology" },
  { demon: "Kumbhakarna", religion: "Hindu mythology" },
  { demon: "Legion", religion: "Christian demonology" },
  { demon: "Lechies", religion: "Slavic mythology" },
  { demon: "Leonard", religion: "Christian demonology" },
  { demon: "Leyak", religion: "Indonesian mythology" },
  { demon: "Lempo", religion: "Finnish mythology" },
  { demon: "Leraje/Leraie", religion: "Christian demonology" },
  { demon: "Leviathan", religion: "Jewish, Gnostic and Christian demonology" },
  { demon: "Lili/Lilin/Lilim", religion: "Jewish mythology" },
  { demon: "Lilith", religion: "Akkadian mythology, Jewish folklore" },
  { demon: "Ljubi", religion: "Albanian mythology" },
  { demon: "Lucifer", religion: "Christian theology" },
  { demon: "Lucifuge", religion: "Christian demonology" },
  { demon: "Malphas", religion: "Christian demonology" },
  { demon: "Mammon", religion: "Christian mythology" },
  { demon: "Mara", religion: "Buddhist mythology" },
  { demon: "Maricha", religion: "Hindu mythology" },
  { demon: "Marax/Morax/Foraii", religion: "Christian demonology" },
  { demon: "Marchosias", religion: "Christian demonology" },
  { demon: "Masih", religion: "Islamic eschatology" },
  { demon: "Mastema", religion: "Jewish demonology" },
  { demon: "Mephistopheles", religion: "Christian folklore, German folklore" },
  { demon: "Merihem", religion: "Christian demonology" },
  {
    demon: "Moloch",
    religion: "Jewish, Pagan and Christian mythology, Scientology"
  },
  { demon: "Murmur", religion: "Christian demonology" },
  { demon: "Naamah", religion: "Jewish mythology" },
  { demon: "Naberius/Cerbere/Naberus", religion: "Christian demonology" },
  { demon: "Ninurta", religion: "Sumerian mythology, Akkadian mythology" },
  { demon: "Namtar", religion: "Sumerian mythology" },
  { demon: "Oni", religion: "Japanese folklore" },
  { demon: "Onoskelis", religion: "Jewish mythology" },
  { demon: "Orcus", religion: "Roman mythology, later Christian demonology" },
  { demon: "Orias/Oriax", religion: "Christian demonology" },
  { demon: "Orobas", religion: "Christian demonology" },
  { demon: "Ose", religion: "Christian demonology" },
  { demon: "Ördög", religion: "Hungarian mythology" },
  { demon: "O Tokata", religion: "Indonesian mythology" },
  { demon: "Paimon", religion: "Christian demonology" },
  { demon: "Pazuzu", religion: "Babylonian demonology" },
  { demon: "Pelesit", religion: "Indonesian and Malaysian mythology" },
  { demon: "Phenex", religion: "Christian demonology" },
  { demon: "Penemue", religion: "Jewish and Christian mythology" },
  { demon: "Pithius", religion: "Christian demonology" },
  { demon: "Pocong", religion: "Indonesian & Malaysia mythology" },
  { demon: "Pontianak", religion: "Indonesian and Malaysian mythology" },
  { demon: "Preta", religion: "Buddhist demonology" },
  { demon: "Pruflas", religion: "Christian demonology" },
  { demon: "Puloman", religion: "Hindu mythology" },
  { demon: "Peth", religion: "French demonology" },
  { demon: "Rahab", religion: "Jewish folklore" },
  { demon: "Raum", religion: "Christian demonology" },
  { demon: "Ronove", religion: "Christian demonology" },
  { demon: "Rusalka", religion: "Slavic mythology" },
  { demon: "Rakshasa", religion: "Hindu mythology" },
  { demon: "Rangda", religion: "Indonesian mythology" },
  { demon: "Sabnock", religion: "Christian demonology" },
  { demon: "Saleos", religion: "Christian demonology" },
  { demon: "Samael", religion: "Jewish and Gnostic mythology" },
  { demon: "Salpsan", religion: "Christian demonology" },
  {
    demon: "Satan",
    religion: "Jewish, Christian, and Islamic theology"
  },
  { demon: "Set", religion: "Egyptian mythology" },
  { demon: "Seir", religion: "Christian demonology" },
  { demon: "Semyaza", religion: "Jewish mythology" },
  { demon: "Shax/Chax", religion: "Christian demonology" },
  { demon: "Shaitan", religion: "Jewish, Islamic demonology" },
  { demon: "Shedim", religion: "Jewish folklore" },
  { demon: "Silver", religion: "Buddhism demonology" },
  { demon: "Sitri", religion: "Christian demonology" },
  { demon: "Sthenno", religion: "Greek mythology" },
  { demon: "Stihi", religion: "Albanian mythology" },
  { demon: "Stolas/Solas", religion: "Christian demonology" },
  { demon: "Suanggi", religion: "Indonesian mythology" },
  { demon: "Succubus", religion: "Christian folklore" },
  { demon: "Surgat", religion: "Christian demonology" },
  { demon: "Shinigami", religion: "Japanese mythology" },
  { demon: "Shuten", religion: "Japanese Mythology" },
  { demon: "Tannin", religion: "Cannanite, Phoenician, Jewish mythology" },
  { demon: "El Tío", religion: "Folk Catholicism" },
  { demon: "Titivillus", religion: "None" },
  { demon: "Toyol", religion: "Indonesian and Malaysian mythology" },
  { demon: "Tuchulcha", religion: "Etruscan mythology" },
  { demon: "Ukobach", religion: "Christian demonology" },
  { demon: "Valac", religion: "Christian demonology" },
  { demon: "Valefar/Malaphar/Malephar", religion: "Christian demonology" },
  { demon: "Vanth", religion: "Etruscan mythology" },
  { demon: "Vapula", religion: "Christian demonology" },
  { demon: "Vassago", religion: "Christian demonology" },
  { demon: "Vepar", religion: "Christian demonology" },
  { demon: "Vine", religion: "Christian demonology" },
  { demon: "Wechuge", religion: "Athabaskan mythology" },
  { demon: "Wendigo", religion: "Algonquin mythology" },
  { demon: "Yeqon", religion: "Jewish mythology" },
  { demon: "Zagan", religion: "Christian demonology" },
  { demon: "Zepar", religion: "Christian demonology" },
  { demon: "Ziminiar", religion: "Christian demonology" },
  { demon: "Zozo", religion: "Christian Demonology" }
];
