export default [
  { demon: "Aamon/Amon", religion: "Christian demonology" },
  { demon: "Abaddon/Apollyon", religion: "Christian demonology" },
  { demon: "Abezethibou", religion: "Jewish demonology" },
  { demon: "Abraxas", religion: "Gnosticism" },
  { demon: "Abyzou", religion: "Jewish mythology" },
  {
    demon: "Adrammelech",
    religion: "Assyrian mythology, Christian demonology"
  },
  { demon: "Aeshma", religion: "Zoroastrianism" },
  { demon: "Agaliarept", religion: "Jewish mythology" },
  { demon: "Agrat-bat-Mahlat", religion: "Jewish demonology" },
  { demon: "Agares", religion: "Christian demonology" },
  { demon: "Agiel", religion: "Jewish mythology" },
  { demon: "Ahriman/Angra", religion: "Zoroastrianism" },
  { demon: "Aka-Manah", religion: "Zoroastrianism" },

  { demon: "Ala", religion: "Slavic mythology" },
  { demon: "Alal", religion: "Chaldean mythology" },
  { demon: "Alastor", religion: "Christian demonology" },
  { demon: "Allocer/Alloces", religion: "Christian demonology" },
  { demon: "Alû", religion: "Akkadian mythology" },
  { demon: "Amaymon", religion: "Christian demonology" },
  { demon: "Amy-(demon)", religion: "Christian demonology" },
  { demon: "Anammelech", religion: "Assyrian mythology" },

  { demon: "Andhaka", religion: "Hindu mythology" },

  { demon: "Antichrist", religion: "Christian eschatology" },
  { demon: "Anzu", religion: "Sumerian mythology" },
  { demon: "Apep", religion: "Egyptian mythology" },
  { demon: "Armaros", religion: "Jewish demonology" },
  { demon: "Archon", religion: "Gnosticism" },
  { demon: "Arunasura", religion: "Hindu mythology" },
  { demon: "Asag", religion: "Sumerian demonology" },

  {
    demon: "Asmodeus/Asmodai",
    religion: "Jewish folklore, Christian mythology, Islamic folklore"
  },
  { demon: "Astaroth", religion: "Christian demonology" },
  { demon: "Asura", religion: "Hindu mythology" },
  { demon: "Azazel/Azaz'el", religion: "Jewish mythology, Islamic mythology" },
  { demon: "Azi", religion: "Zoroastrianism" },
  { demon: "Baal-(demon)", religion: "Christian demonology" },
  { demon: "Babi", religion: "Indonesian mythology" },
  { demon: "Bakasura", religion: "Hindu mythology" },
  { demon: "Baku", religion: "Japanese mythology" },
  { demon: "Balam-(demon)", religion: "Christian demonology" },
  { demon: "Baal-Berith", religion: "Jewish demonology" },

  { demon: "Banshee", religion: "Irish mythology" },
  { demon: "Baphomet", religion: "Christian folklore" },

  { demon: "Barbatos", religion: "Christian demonology" },
  { demon: "Barong", religion: "Indonesian mythology" },
  { demon: "Bathin/Mathim/Bathym/Marthim", religion: "Christian demonology" },
  { demon: "Beelzebub", religion: "Jewish and Christian demonology" },
  { demon: "Behemoth", religion: "Jewish and Christian mythology" },
  { demon: "Belial", religion: "Jewish Christian demonology" },
  { demon: "Beleth", religion: "Christian demonology" },
  { demon: "Belphegor", religion: "Christian demonology" },

  { demon: "Bhoot-(ghost)/Bhūta", religion: "Hindu mythology" },
  { demon: "Bifrons-(demon)", religion: "Christian demonology" },

  { demon: "Botis", religion: "Christian demonology" },
  { demon: "Buer-(demon)", religion: "Christian demonology" },
  { demon: "Bukavac", religion: "Slavic mythology" },
  { demon: "Bune", religion: "Christian demonology" },
  { demon: "Bushyasta", religion: "Zoroastrianism" },
  { demon: "Caim/Canio", religion: "Christian demonology, Scientology" },
  { demon: "Charun", religion: "Etruscan mythology" },
  { demon: "Chemosh", religion: "Moabite mythology" },
  { demon: "Choronzon", religion: "Thelema" },
  { demon: "Chort", religion: "Slavic mythology" },

  { demon: "Corson-(demon)", religion: "Christian demonology" },
  { demon: "Crocell/Procell", religion: "Christian demonology" },
  { demon: "Daeva", religion: "Zoroastrianism" },
  { demon: "Dagon", religion: "Semitic mythology" },

  { demon: "Dantalion", religion: "Christian demonology" },

  { demon: "Demiurge", religion: "Gnostic mythology" },
  { demon: "Demogorgon", religion: "Christian demonology" },
  { demon: "Devil", religion: "Christian demonology" },
  { demon: "Div=e-Sepid", religion: "persian mythology" },
  { demon: "Djall", religion: "Albanian mythology" },
  { demon: "Drekavac", religion: "Slavic mythology" },
  { demon: "Dzoavits", religion: "Native American mythology" },

  { demon: "Eisheth", religion: "Jewish demonology" },
  { demon: "Erlik", religion: "Turkish mythology" },

  { demon: "Foras/Forcas/Forras", religion: "Christian demonology" },
  { demon: "Forneus", religion: "Christian demonology" },
  { demon: "Furcas/Forcas", religion: "Christian demonology" },
  { demon: "Furfur", religion: "Christian demonology" },
  { demon: "Gaap", religion: "Christian demonology" },
  { demon: "Gadreel/Gader'el", religion: "Jewish demonology" },

  { demon: "Gamigin", religion: "Christian demonology" },
  { demon: "Ghoul", religion: "Arabian" },
  {
    demon: "Glasya=Labolas/Caacrinolaas",
    religion: "Christian demonology"
  },
  { demon: "Gorgon", religion: "Greek mythology" },
  { demon: "Gremory/Gomory", religion: "Christian demonology" },

  { demon: "Gualichu", religion: "Mapuche mythology" },
  { demon: "Guayota", religion: "Guanche mythology" },
  { demon: "Gusion/Gusoin/Gusoyn", religion: "Christian demonology" },
  { demon: "Haagenti", religion: "Christian demonology" },
  { demon: "Halphas/Malthus", religion: "Christian demonology" },
  { demon: "Hinn-(mythology)", religion: "Islamic folklore" },
  { demon: "Iblis", religion: " Islamic demonology" },
  { demon: "Ifrit", religion: "Islamic mythology" },
  { demon: "Incubus", religion: "Christian demonology" },
  { demon: "Ipos/Ipes", religion: "Christian demonology" },
  { demon: "İye/Kara", religion: "Turkish mythology" },
  { demon: "Jinn", religion: "Islamic demonology" },
  { demon: "Jikininki", religion: "Japanese mythology" },
  { demon: "Kabandha/Kabhanda", religion: "Hindu mythology" },
  { demon: "Kimaris/Cimeies/Cimejes", religion: "Christian demonology" },
  { demon: "Kokabiel", religion: "Jewish mythology" },
  { demon: "Kroni", religion: "Ayyavazhi demonology" },
  { demon: "Krampus", religion: "Germanic-Christian demonology" },
  { demon: "Kukudh", religion: "Albanian mythology" },
  { demon: "Kumbhakarna", religion: "Hindu mythology" },
  { demon: "Legion-(demons)", religion: "Christian demonology" },
  { demon: "Leonard-(demon)", religion: "Christian demonology" },
  { demon: "Leshy", religion: "Slavic mythology" },
  { demon: "Leyak", religion: "Indonesian mythology" },
  { demon: "Lempo", religion: "Finnish mythology" },
  { demon: "Leraje/Leraie", religion: "Christian demonology" },
  { demon: "Leviathan", religion: "Jewish, Gnostic and Christian demonology" },
  { demon: "Lilin/Lilim/Lili", religion: "Jewish mythology" },
  { demon: "Lilith", religion: "Akkadian mythology, Jewish folklore" },
  { demon: "Ljubi", religion: "Albanian mythology" },
  { demon: "Lucifer", religion: "Christian theology" },
  { demon: "Lucifuge-Rofocale", religion: "Christian demonology" },
  { demon: "Mahabali", religion: "Hindu mythology" },
  { demon: "Malphas", religion: "Christian demonology" },
  { demon: "Mammon", religion: "Christian mythology" },
  { demon: "Mara-(demon)", religion: "Buddhist mythology" },
  { demon: "Marbas", religion: "Christian demonology" },
  { demon: "Maricha", religion: "Hindu mythology" },
  { demon: "Morax-(demon)/Morax/Foraii", religion: "Christian demonology" },
  { demon: "Marchosias", religion: "Christian demonology" },
  { demon: "Al=Masih-ad=Dajjal", religion: "Islamic eschatology" },
  { demon: "Mastema", religion: "Jewish demonology" },
  { demon: "Mephistopheles", religion: "Christian folklore, German folklore" },

  {
    demon: "Moloch",
    religion: "Jewish, Pagan and Christian mythology, Scientology"
  },
  { demon: "Murmur-(demon)", religion: "Christian demonology" },
  { demon: "Naamah-(demon)", religion: "Jewish mythology" },
  { demon: "Naberius/Cerbere/Naberus", religion: "Christian demonology" },
  { demon: "Ninurta", religion: "Sumerian mythology, Akkadian mythology" },
  { demon: "Namtar", religion: "Sumerian mythology" },
  { demon: "Oni", religion: "Japanese folklore" },
  { demon: "Onoskelis", religion: "Jewish mythology" },
  { demon: "Orcus", religion: "Roman mythology, later Christian demonology" },
  { demon: "Orias/Oriax", religion: "Christian demonology" },
  { demon: "Orobas", religion: "Christian demonology" },
  { demon: "Ose-(demon)", religion: "Christian demonology" },
  { demon: "Ördög", religion: "Hungarian mythology" },
  { demon: "O-Tokata", religion: "Indonesian mythology" },
  { demon: "Paimon", religion: "Christian demonology" },
  { demon: "Pazuzu", religion: "Babylonian demonology" },
  { demon: "Pelesit", religion: "Indonesian and Malaysian mythology" },
  { demon: "Phenex", religion: "Christian demonology" },
  { demon: "Penemue", religion: "Jewish and Christian mythology" },
  { demon: "Pocong", religion: "Indonesian & Malaysia mythology" },
  {
    demon: "Pontianak-(folklore)",
    religion: "Indonesian and Malaysian mythology"
  },
  { demon: "Preta", religion: "Buddhist demonology" },
  { demon: "Purson", religion: "Christian demonology" },
  { demon: "Puloman", religion: "Hindu mythology" },
  { demon: "Rahab", religion: "Jewish folklore" },
  { demon: "Raum", religion: "Christian demonology" },
  { demon: "Ronove", religion: "Christian demonology" },
  { demon: "Rusalka", religion: "Slavic mythology" },
  { demon: "Rakshasa", religion: "Hindu mythology" },
  { demon: "Rangda", religion: "Indonesian mythology" },

  { demon: "Samael", religion: "Jewish and Gnostic mythology" },

  {
    demon: "Satan",
    religion: "Jewish, Christian, and Islamic theology"
  },
  { demon: "Set-(deity)", religion: "Egyptian mythology" },

  { demon: "Samyaza", religion: "Jewish mythology" },
  { demon: "Shax/Chax", religion: "Christian demonology" },
  { demon: "Shaitan", religion: "Jewish, Islamic demonology" },
  { demon: "Shedim", religion: "Jewish folklore" },
  { demon: "Stheno", religion: "Greek mythology" },
  { demon: "Stihi", religion: "Albanian mythology" },
  { demon: "Stolas/Solas", religion: "Christian demonology" },
  { demon: "Suanggi", religion: "Indonesian mythology" },
  { demon: "Succubus", religion: "Christian folklore" },
  { demon: "Surgat", religion: "Christian demonology" },
  { demon: "Shinigami", religion: "Japanese mythology" },
  { demon: "Shuten=dōji", religion: "Japanese Mythology" },
  {
    demon: "Tannin-(monster)",
    religion: "Cannanite, Phoenician, Jewish mythology"
  },
  { demon: "El Tío", religion: "Folk Catholicism" },
  { demon: "Titivillus", religion: "None" },
  { demon: "Toyol", religion: "Indonesian and Malaysian mythology" },
  { demon: "Tuchulcha", religion: "Etruscan mythology" },
  { demon: "Ukobach", religion: "Christian demonology" },
  { demon: "Valac", religion: "Christian demonology" },
  { demon: "Valefar/Malaphar/Malephar", religion: "Christian demonology" },
  { demon: "Vanth", religion: "Etruscan mythology" },
  { demon: "Vapula", religion: "Christian demonology" },
  { demon: "Vassago", religion: "Christian demonology" },
  { demon: "Vepar", religion: "Christian demonology" },
  { demon: "Vine-(demon)", religion: "Christian demonology" },
  { demon: "Wechuge", religion: "Athabaskan mythology" },
  { demon: "Wendigo", religion: "Algonquin mythology" },

  { demon: "Ziminiar", religion: "Christian demonology" }
];
